#!/usr/bin/env bash
# This script configures domain zone subdomains and display subdomain
display_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type="$(dig +short "$subdomain.$domain" | awk 'NR==1 {print toupper($1)}')"
    local destination="$(dig +short "$subdomain.$domain" | awk 'NR==1 {print $1}')"
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Function to display information about default subdomains
display_default_subdomains_info() {
    local domain="$1"
    display_subdomain_info "$domain" "www"
    display_subdomain_info "$domain" "lb-01"
    display_subdomain_info "$domain" "web-01"
    display_subdomain_info "$domain" "web-02"
}

# Main function
main() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        # Display information for default subdomains if only domain is provided
        display_default_subdomains_info "$domain"
    else
        # Display information for the specified subdomain
        display_subdomain_info "$domain" "$subdomain"
    fi
}

# Check if both domain and subdomain parameters are provided
if [ $# -lt 1 ] || [ $# -gt 2 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

# Execute main function
main "$@"

