#!/usr/bin/env bash
# Configure web-02 to be identical to web-01
# Add custom Nginx response header

# Update package information
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx to include the custom response header
custom_header="add_header X-Served-By \$HOSTNAME;"
sudo sed -i "/server_name _/a $custom_header" /etc/nginx/sites-enabled/default

# Test Nginx configuration for syntax errors
sudo nginx -t

# Restart Nginx to apply changes
sudo service nginx restart
