#!/usr/bin/env bash
# Deploy load balancer

# Install and configure HAProxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# Edit config file
server_config=\
"
frontend besthor_frontend
    bind *:80
    mode http
    default_backend codefox254_backend

backend besthor_backend
    balance roundrobin
    server web-01 34.239.248.207:80 check
    server web-02 35.175.128.155:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by the init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Test the HAProxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo service haproxy restart
