#!/usr/bin/env bash
# Script to backup and compress databases

# Variables
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="${day}-${month}-${year}.tar.gz"

# Database dump and compression
mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "${file_name}" backup.sql
