#!/usr/bin/env bash
# Ping an IP address and display results

if [ $# -eq 0 ]; then
    echo "Usage: $(basename $0) {IP_ADDRESS}"
    exit 1
fi

ip_address="$1"

# Ping the IP address 5 times
ping_result=$(ping -c 5 "$ip_address")

# Display the ping results
echo "$ping_result"

