#!/usr/bin/env bash
# Ensures Nginx is running and listening on port 80
sudo systemctl restart nginx
sudo sed -i 's/listen [::]:80;/listen 80;/' /etc/nginx/sites-available/default
sudo systemctl reload nginx

