#!/usr/bin/env bash
# Configure Nginx server to listen on port 80.

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
sleep 1
kill -s QUIT $(pgrep nginx | head -n 1)
