#!/bin/sh
### BEGIN INIT INFO
# Provides:          manage_my_process
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage manage_my_process daemon
### END INIT INFO

# Change the path to the manage_my_process script accordingly
SCRIPT="/path/to/manage_my_process"

# Check if the script is executable
test -x "$SCRIPT" || exit 0

case "$1" in
  start)
    "$SCRIPT" start
    ;;
  stop)
    "$SCRIPT" stop
    ;;
  restart)
    "$SCRIPT" restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0

