#!/usr/bin/env bash
# This script displays lines containing the 'bash' word to get the PID of Bash process
# shellcheck disable=SC2009

# Using ps command to find lines containing the 'bash' word
ps aux | grep '[b]ash'

