#!/usr/bin/env bash
# Using a while loop to read each line of the file /etc/passwd with IFS
while IFS=: read -r username password uid gid gecos home shell; do
    # Extracting additional information from the gecos field
    IFS=',' read -ra gecos_array <<< "$gecos"
    user_info="${gecos_array[0]}"

    # Extracting additional information from the shell field
    IFS='/' read -ra shell_array <<< "$shell"
    user_shell="${shell_array[-1]}"

    # Displaying the formatted information for each user
    echo "The user $username is part of the group $gid gang, lives in $home and rides $user_shell."
    echo "User ID's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
