#!/usr/bin/env bash
# Using awk to group visitors by IP and HTTP status code, count occurrences, and sort the data
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
