#!/usr/bin/env bash
# Initialize variables for hours and minutes
hour=0
minute=1

# Using a while loop to display the time
while [ $hour -le 12 ]; do
    while [ $minute -le 59 ]; do
        printf "%02d:%02d\n" $hour $minute
        ((minute++))
        if [ $minute -gt 59 ]; then
            ((hour++))
            minute=0
        fi
        if [ $hour -gt 12 ]; then
            break
        fi
    done
done | head -n 70
