#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
hour=0
minute=1
while [ $hour -le 12 ]
do
    while [ $minute -le 59 ]
    do
        echo "$hour hour(s) and $minute minute(s)"
        ((minute++))
    done
    minute=1
    ((hour++))
done | head -n 70

