#!/usr/bin/env bash
# Backup the current /etc/hosts file
# Replace the existing localhost entry with 127.0.0.2
# Add or replace the facebook.com entry to resolve to 8.8.8.8
# Display the updated /etc/hosts file

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts