#!/bin/bash
# Get active IPv4 addresses using ifconfig
ipv4_addresses=$(ifconfig | grep -oP '(?<=inet\s)\d+\.\d+\.\d+\.\d+' | grep -v '127.0.0.1')

# Display active IPv4 addresses
echo "$ipv4_addresses"

